# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Actually 杨泽楷
email: 474958457@qq.com
description: > # this means to ignore newlines until "baseurl:"
    Android developer
  baseurl: ""
url: "http://yangzekai.github.io"
github_username: yangzekai

markdown: kramdown

gems:
  - jekyll-angular
