# user variables, change this to make custom site.

name: Yann
desc: Yann's blog
author:
  name: Yann
  avatar: //gravatar.com/avatar/daa1cc36ed2ab0d13045d5cd2431cde9?s=320
  profile: |
    杨泽楷的技术博客
  socials:
    facebook:
    twitter: 
    google-plus:
    github: //github.com/yangzekai
    stack-overflow:
    instagram:
    pinterest:
    steam: 
license: MIT License


# theme variables, change this to make site looks best.
baseurl: /lemma-theme
paginate: 2


# system variables, do not change unless you knew what's it does.
paginate_path: page/:num
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed
